/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.sopin;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("App should return a greeting", classUnderTest.handleRequest("Hello", null));
    }
}
